[package]
name = "hatebu2bsky"
version = "0.1.0"
edition = "2021"
description = "Hatena bookmark to bluesky"

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
atrium-api = "0.18.0"
atrium-xrpc-client = "0.4.0"
worker = "0.0.18"
getrandom = { version = "0.2", features = ["js"] }
reqwest = { version = "0.11.24", default-features = false }
rss = { version = "2.0.7", default-features = false }
webpage = { version = "2.0.0", default-features = false }

[profile.release]
lto = true
strip = true
codegen-units = 1
